// IN PROGRESS
export const FETCHING_QUERY = 'FETCHING_QUERY';

// CANCEL
export const QUERY_FETCH_CANCEL = 'QUERY_FETCH_CANCEL';

// FULFILLED
export const QUERY_FETCH_FULFILLED = 'QUERY_FETCH_FULFILLED';

// ERROR
export const QUERY_FETCH_ERROR = 'QUERY_FETCH_ERROR';